ДЗ-3. Выделить привязанный сервис для загрузки списка контактов.
melomory/AndroidApp pull request #3
Opened 2021-11-03 09:06 UTC by melomory

# Домашнее задание 3
## Выделить привязанный сервис для загрузки списка контактов
Необходимо написать привязанный сервис, который будет иметь публичное API предоставляющее список контактов.
Список контактов пока захардкодить в константу
Сервис должен предоставлять список контактов на другом потоке программы - т.е. должен создавать поток для загрузки списка контактов

Сценарий использования:
- Главная активность привязывается к сервису с помощью bindService
- Получает публичный интерфейс сервиса
- Предоставляет публичный интерфейс сервиса фрагментам
- Фрагменты используют публичный интерфейс сервиса для получения данных контактов

Публичный интерфейс должен иметь 2 метода:
1. Метод получения списка контактов с короткой информацией (будет использоваться в фрагменте списка контактов) - метод должен быть асинхронным
2. Метод получения детальной информации по ID контакта (будет использоваться в фрагменте деталей контакта) - метод должен быть асинхронным

2021-11-03 19:21 UTC, alex-sus commented
Замечательно, но при повороте смартфона на экране 2 почему-то возникает экран 1. Разберись с этим.

2021-11-03 20:47 UTC, alex-sus requested changes

2021-11-03 20:47 UTC, alex-sus commented on app/src/main/java/com/gmail/niko/den/vl/Contact.kt
> +data class Contact(val contactId: String = "",
После скобки нужно сделать перевод строки

2021-11-03 20:47 UTC, alex-sus commented on app/src/main/java/com/gmail/niko/den/vl/Contact.kt
> +                   var name: String = "",
var в дата-классе применять не стоит, это ведет к багам, которые трудно найти. Везде только val.

2021-11-03 20:47 UTC, alex-sus commented on app/src/main/java/com/gmail/niko/den/vl/Contact.kt
> +                   var phoneNumber: String = "")
Перед скобкой нужно сделать перевод строки

2021-11-03 20:47 UTC, alex-sus commented on app/src/main/java/com/gmail/niko/den/vl/ContactDetailsFragment.kt
> +        view.findViewById<TextView>(R.id.contactPhoneNumber1).text = contact?.phoneNumber
Выглядит так себе. findViewById в таких ситуациях сейчас стараются не использовать.
Почитай про View Binding и используй его, если хочешь быть современным

2021-11-03 20:47 UTC, alex-sus commented on app/src/main/java/com/gmail/niko/den/vl/ContactListListener.kt
>  interface ContactListListener {
Не нужно смешивать всё в один интерфейс.
Прочти про принципы SOLID и первый из них - Single Responsibility.
Для сервиса создай отдельный интерфейс, вынеси туда его методы и соответственно внеси изменения в коде

2021-11-03 20:47 UTC, alex-sus commented on app/src/main/java/com/gmail/niko/den/vl/GetContactListService.kt
> +    suspend fun getContactList(): List<Contact> {
У тебя эти функции не suspend и Андроид Студио на это прямо указывает. Чего-то не хватает

2021-11-03 20:47 UTC, alex-sus commented on app/src/main/java/com/gmail/niko/den/vl/GetContactListService.kt
> +    suspend fun getContactDetails(contactId: String): Contact? {
Чего-то не хватает

2021-11-03 20:47 UTC, alex-sus commented on app/src/main/java/com/gmail/niko/den/vl/MainActivity.kt
> +                    .commit()
Это лучше вынести в отдельную функцию навигации, как в случае с экраном детализации

2021-11-06 16:52 UTC, alex-sus commented on app/src/main/java/com/gmail/niko/den/vl/GetContactListService.kt
> +    suspend fun getContactList(): List<Contact> {
Либо другой вариант: ничего не менять, только убрать suspend. Пусть это будут обычные функции

2021-11-06 16:53 UTC, alex-sus commented on app/src/main/java/com/gmail/niko/den/vl/GetContactListService.kt
> +    suspend fun getContactDetails(contactId: String): Contact? {
Здесь лучше просто убрать suspend и всё

2021-11-07 17:08 UTC, melomory commented on app/src/main/java/com/gmail/niko/den/vl/Contact.kt
> +data class Contact(val contactId: String = "",
Исправил

2021-11-07 17:08 UTC, melomory commented on app/src/main/java/com/gmail/niko/den/vl/Contact.kt
> +                   var name: String = "",
Исправил

2021-11-07 17:08 UTC, melomory commented on app/src/main/java/com/gmail/niko/den/vl/Contact.kt
> +                   var phoneNumber: String = "")
Исправил

2021-11-07 17:08 UTC, melomory commented on app/src/main/java/com/gmail/niko/den/vl/ContactDetailsFragment.kt
> +        view.findViewById<TextView>(R.id.contactPhoneNumber1).text = contact?.phoneNumber
Исправил

2021-11-07 17:09 UTC, melomory commented on app/src/main/java/com/gmail/niko/den/vl/ContactListListener.kt
>  interface ContactListListener {
Сделал отдельный интерфейс

2021-11-07 17:11 UTC, melomory commented on app/src/main/java/com/gmail/niko/den/vl/GetContactListService.kt
> +    suspend fun getContactList(): List<Contact> {
Замечание не понял. В данной функции предполагается нахождение асинхронного кода. Пока сделана функция delay, которая требует от вызывающей функции быть suspended.

2021-11-07 17:11 UTC, melomory commented on app/src/main/java/com/gmail/niko/den/vl/GetContactListService.kt
> +    suspend fun getContactDetails(contactId: String): Contact? {
Так же не понял

2021-11-07 17:11 UTC, melomory commented on app/src/main/java/com/gmail/niko/den/vl/MainActivity.kt
> +                    .commit()
Исправил

2021-11-07 17:12 UTC, melomory commented
Сделал исправления.

2021-11-07 20:55 UTC, alex-sus requested changes

2021-11-07 20:55 UTC, alex-sus commented on app/src/main/java/com/gmail/niko/den/vl/ContactDetailsFragment.kt
> +    private lateinit var viewBinding: FragmentContactDetailsBinding
Чтобы память освобождалась, принято делать  viewBinding = null в onDestroyView()

2021-11-07 20:55 UTC, alex-sus commented on app/src/main/java/com/gmail/niko/den/vl/ContactDetailsFragment.kt
> +        contactListListener = null
super.onDetach() здесь должна идти последней

2021-11-07 20:55 UTC, alex-sus commented on app/src/main/java/com/gmail/niko/den/vl/ContactListFragment.kt
> +    private lateinit var viewBinding: FragmentContactListBinding
Чтобы память освобождалась, принято делать viewBinding = null в onDestroyView()

2021-11-07 20:55 UTC, alex-sus commented on app/src/main/java/com/gmail/niko/den/vl/ContactListFragment.kt
> +                    ?.navigateToContactDetailsFragment(contactList?.get(0)?.contactId.toString())
С вопросительного знака нельзя начинать строку. Подними его на строку выше

2021-11-07 20:55 UTC, alex-sus commented on app/src/main/java/com/gmail/niko/den/vl/ContactListFragment.kt
>          contactListListener = null
super.onDetach() здесь должна идти последней

2021-11-07 20:55 UTC, alex-sus commented on app/src/main/java/com/gmail/niko/den/vl/GetContactListService.kt
> +    suspend fun getContactList(): List<Contact> {
Ок, про delay я  забыл

2021-11-07 20:55 UTC, alex-sus commented on app/src/main/java/com/gmail/niko/den/vl/MainActivity.kt
> +    override fun navigateToContactList() {
Определись с названиями. 
Эта функция у тебя называется navigateToContactList, а следующая - navigateToContactDetailsFragment.
Названия должны даваться единообразно. Фрагмент, так везде фрагмент.
Первая ф-ция должна называться navigateToContactListFragment

2021-11-07 21:01 UTC, alex-sus commented
Гораздо лучше. Осталось дошлифовать мелкие детали

2021-11-08 17:43 UTC, melomory commented on app/src/main/java/com/gmail/niko/den/vl/ContactListFragment.kt
> +    private lateinit var viewBinding: FragmentContactListBinding
Исправил

2021-11-08 17:43 UTC, melomory commented on app/src/main/java/com/gmail/niko/den/vl/ContactListFragment.kt
> +                    ?.navigateToContactDetailsFragment(contactList?.get(0)?.contactId.toString())
Исправил

2021-11-08 17:43 UTC, melomory commented on app/src/main/java/com/gmail/niko/den/vl/ContactListFragment.kt
>          contactListListener = null
Исправил

2021-11-08 17:43 UTC, melomory commented on app/src/main/java/com/gmail/niko/den/vl/MainActivity.kt
> +    override fun navigateToContactList() {
Исправил

2021-11-08 17:48 UTC, melomory commented on app/src/main/java/com/gmail/niko/den/vl/ContactDetailsFragment.kt
> +    private lateinit var viewBinding: FragmentContactDetailsBinding
Исправил. При исследовании темы утечек памяти данного кода появился вопрос.
LeakCanary сообщает, что существует утечка памяти, связанной с привязанным сервисом. Как я понял это связано с внутренним классом.  Следует ли вынести IBinder из класса сервиса в отдельный класс?

2021-11-08 17:48 UTC, melomory commented
Исправил.

2021-11-08 19:01 UTC, alex-sus commented on app/src/main/java/com/gmail/niko/den/vl/ContactDetailsFragment.kt
> +    private lateinit var viewBinding: FragmentContactDetailsBinding
Не следует.
Попробуй сделать binder = null в onUnbind в сервисе

2021-11-08 19:44 UTC, merged