ДЗ-4. Напоминалка о дне рождения контакта
melomory/AndroidApp pull request #4
Opened 2021-11-14 14:35 UTC by melomory

# Домашнее задание 4
## Напоминалка о дне рождения контакта

Необходимо добавить к деталям контакта:

- поле "День рождения" в формате "число месяц";
- кнопку, которая будет иметь 2 состояния - "Включить напоминания" и "Выключить напоминания". Состояние кнопки должно зависеть от того, добавлена ли уже задача в AlarmManager или нет.

При нажатии кнопки в состоянии "Включить напоминания" - должна ставиться задача на вызов вашего BroadcastReceiver'а на число в поле "День рождения" в качестве данных в Intent должен передаваться ID выбранного контакта и текст напоминания "Сегодня день рождения у $s", где $s - имя контакта
При нажатии кнопки в состоянии "Выключить напоминания" - должна производиться отмена предстоящей задачи в AlarmManager и состояние кнопки должно обновиться на "Включить напоминания".
https://developer.android.com/training/scheduling/alarms

Ваш BroadcastReceiver в свою очередь должен запустить Notification (специальное уведомление, которое показывается в шторке уведомлений) с текстом пришедшем ему из Intent.
https://developer.android.com/training/notify-user/build-notification

При нажатии пользователем на уведомление - должна запуститься активность вашего приложения, при этом должен сразу открыться экран с деталями контакта у которого день рождение, уведомление при этом должно исчезнуть из шторки уведомлений. 
https://developer.android.com/reference/android/app/Activity#getIntent()

2021-11-15 18:29 UTC, alex-sus commented
Интересно, как ты проверил, что условия задачи выполняются:
- Напоминания устанавливаются и отменяются.
- Напоминаний можно установить одновременно несколько, ведь потом контактов будет много.
- Напоминание появляется на экране в заданное время даже при выгруженном приложении.
- По нажатию на Напоминание происходит переход именно на экран с деталями указанного контакта, а не на список контактов.
Я пробовал поставить текущую дату и время, но Напоминание не появилось.
Нас интересует реально работающее приложение.

2021-11-15 20:19 UTC, alex-sus requested changes

2021-11-15 20:19 UTC, alex-sus commented on app/src/main/java/com/gmail/niko/den/vl/ContactDetailsFragment.kt
>              contactDescription.text = getString(R.string.contact_details_description)
Эта информация должна приходить из сервиса, а не прописываться здесь напрямую. Переделать.

2021-11-15 20:19 UTC, alex-sus commented on app/src/main/java/com/gmail/niko/den/vl/ContactDetailsFragment.kt
> +                                activity,
Вместо неудобного пикера предлагаю просто к текущему времени прибавлять количество секунд, указанных в константе (которую нужно создать). Для начала пусть там будет 20 секунд. Таким образом, мы сможем легко проверить в реальности как срабатывает напоминание просто подождав несколько секунд, а не борясь с пикером. Естественно в качестве даты рождения контакта нужно будет устанавливать текущую дату, но это я могу изменить вручную, когда буду проверять.

2021-11-15 20:19 UTC, alex-sus commented on app/src/main/java/com/gmail/niko/den/vl/NotificationAssistant.kt
> +                301,
В константу с понятным названием

2021-11-15 20:19 UTC, alex-sus commented on app/src/main/java/com/gmail/niko/den/vl/AlarmAssistant.kt
> +                putExtra("REMINDER_MESSAGE", "Сегодня день рождения у ${it.name}")
Надпись - в ресурсы

2021-11-18 17:41 UTC, melomory commented on app/src/main/java/com/gmail/niko/den/vl/ContactDetailsFragment.kt
>              contactDescription.text = getString(R.string.contact_details_description)
Информация приходит из сервиса выше в методе onViewCreated. В корутине получается объект contact, и затем выполняется заполнение полей, разве не так?

2021-11-18 17:42 UTC, melomory commented on app/src/main/java/com/gmail/niko/den/vl/AlarmAssistant.kt
> +                putExtra("REMINDER_MESSAGE", "Сегодня день рождения у ${it.name}")
Полностью "Сегодня день рождения у ${it.name}" или как-то можно сделать по-другому?

2021-11-18 17:44 UTC, melomory commented on app/src/main/java/com/gmail/niko/den/vl/NotificationAssistant.kt
> +                301,
Можно пояснение? Мне не понятно как здесь должен выбираться id. Ясно, что он должен быть уникальным, но чем руководствоваться при его выборе?

2021-11-19 16:46 UTC, melomory commented
> Интересно, как ты проверил, что условия задачи выполняются:
> 
>     * Напоминания устанавливаются и отменяются.
Использовал логгирование, в том числе в методе onReceive. И тестировал на устройстве, изменяя дату и время.

>     * Напоминание появляется на экране в заданное время даже при выгруженном приложении.
> 
Возможно следовало использовать метод setExact для точного срабатывания оповещения, так как метод set с API 19 обрабатывается как неточный.
>     * По нажатию на Напоминание происходит переход именно на экран с деталями указанного контакта, а не на список контактов.
Демонстрация:

https://user-images.githubusercontent.com/55689738/142659645-7a0c41a7-33a0-4891-9f4d-83e51be3fcc3.mp4

2021-11-20 12:05 UTC, alex-sus commented on app/src/main/java/com/gmail/niko/den/vl/NotificationAssistant.kt
> +                301,
Очевидно любым способом, который позволит достичь указанного тобою свойства - уникальности )
Т.к. идентификатор к сожалению должен быть Int, один из допустимых способов здесь - использовать id.hashCode() от стрингового идентификатора контакта. 
Это конечно вариант на будущее, когда контактов у тебя будет много, но можно сделать прямо сейчас, тогда в константу ничего выносить не нужно

2021-12-11 11:44 UTC, melomory commented
Исправил основные замечание.
Не могу понять, почему не работает wrap текста в части имени контакта.

2021-12-12 11:36 UTC, alex-sus commented
По имени контакта делается так: обрати внимание на измененные мною параметры TextView:
(Можно исправить в следующем PR)

![image](https://user-images.githubusercontent.com/79583896/145710541-b7b63d6b-f49d-4e50-8ac6-0e9d8c2f72d8.png)

2021-12-12 11:37 UTC, merged